services:
  service:
    restart: on-failure
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      pgpool:
        condition: service_started  
      redis:
        condition: service_started
    env_file:
      - ./backend/.env
    networks:
      - eskrim
  
  postgres-master:
    image: bitnami/postgresql:latest
    environment:
      POSTGRESQL_USERNAME: ${POSTGRESQL_USERNAME}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRESQL_REPLICATION_USER: ${POSTGRESQL_REPLICATION_USER}
      POSTGRESQL_REPLICATION_PASSWORD: ${POSTGRESQL_REPLICATION_PASSWORD}
      POSTGRESQL_REPLICATION_MODE: master
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - postgres_master_data:/bitnami/postgresql
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - eskrim
  
  postgres-slave:
    image: bitnami/postgresql:latest
    environment:
      POSTGRESQL_USERNAME: ${POSTGRESQL_USERNAME}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRESQL_REPLICATION_USER: ${POSTGRESQL_REPLICATION_USER}
      POSTGRESQL_REPLICATION_PASSWORD: ${POSTGRESQL_REPLICATION_PASSWORD}
      POSTGRESQL_REPLICATION_MODE: slave
      POSTGRESQL_MASTER_HOST: postgres-master
      POSTGRESQL_MASTER_POST_NUMBER: 5432
    volumes:
      - postgres_slave_data:/bitnami/postgresql
    depends_on:
      postgres-master:
        condition: service_healthy
    networks:
      - eskrim

  pgpool:
    image: mrgreen007/pgpool:latest
    environment:
      PGPOOL_BACKEND_NODES: 0:postgres-master:5432,1:postgres-slave:5432
      PGPOOL_SR_CHECK_USER: ${POSTGRESQL_REPLICATION_USER}
      PGPOOL_SR_CHECK_PASSWORD: ${POSTGRESQL_REPLICATION_PASSWORD}
      PGPOOL_POSTGRES_USERNAME: ${POSTGRESQL_USERNAME}
      PGPOOL_POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      PGPOOL_ADMIN_USERNAME: ${PGPOOL_ADMIN_USERNAME}
      PGPOOL_ADMIN_PASSWORD: ${PGPOOL_ADMIN_PASSWORD}
    depends_on:
      postgres-master:
        condition: service_healthy
      postgres-slave:
        condition: service_started
    ports:
      - "5432:5432"
    networks:
      - eskrim
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - eskrim
    
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - eskrim

  seaweedfs-master:
    image: chrislusf/seaweedfs:latest
    command: 'master -ip="seaweedfs-master" -ip.bind=0.0.0.0 -port=9333'
    ports:
      - "9333:9333"
    networks:
      - eskrim

  seaweedfs-filer:
    image: chrislusf/seaweedfs:latest
    command: 'filer -ip="seaweedfs-filer" -master="seaweedfs-master" -ip.bind=0.0.0.0 -port=8888'
    ports:
      - "8888:8888"
    depends_on:
      - seaweedfs-master
      - seaweedfs-volume
    networks:
      - eskrim

  seaweedfs-volume:
    image: chrislusf/seaweedfs:latest
    command: 'volume -master="seaweedfs-master:9333" -ip=seaweedfs-volume -ip.bind=0.0.0.0 -port=8081'
    ports:
      - "8081:8081"
    depends_on:
      - seaweedfs-master
    networks:
      - eskrim

  seaweedfs-s3:
    image: chrislusf/seaweedfs:latest
    command: 's3 -filer="filer:8888" -ip.bind=0.0.0.0 -port=8333 -config="/etc/seaweedfs/s3.json"'
    ports:
      - "8333:8333"
    volumes:
      - ./seaweedfs/s3.json:/etc/seaweedfs/s3.json
    depends_on:
      - seaweedfs-master
      - seaweedfs-volume
      - seaweedfs-filer
    networks:
      - eskrim

networks:
  eskrim:
    driver: bridge

volumes:
  redis_data:
    driver: local
  postgres_master_data:
  postgres_slave_data: