INSERT INTO ice_creams (name, flavour, picture_url, price, description) VALUES
('Slime Gelato', 'Mint', '/slime.png', 4.50, 'A refreshing minty slime experience.'),
('Slime Sundae', 'Vanilla', '/slime.png', 5.00, 'Classic vanilla topped with green slime syrup.'),
('Ooze Cone', 'Matcha', '/slime.png', 3.75, 'Sweet and earthy matcha flavor in a slime cone.'),
('Toxic Waste', 'Sour Apple', '/slime.png', 4.00, 'Super sour green apple slime ice cream.'),
('Slime Popsicle', 'Lime', '/slime.png', 2.50, 'Zesty lime flavored slime on a stick.'),
('Gooey Scoop', 'Pistachio', '/slime.png', 4.80, 'Rich pistachio with a gooey slime texture.'),
('Mutant Swirl', 'Kiwi', '/slime.png', 5.20, 'Tropical kiwi swirled with slime.'),
('Swamp Monster', 'Chocolate Mint', '/slime.png', 5.50, 'Dark chocolate and mint slime.'),
('Radioactive Sludge', 'Green Tea', '/slime.png', 4.25, 'Smooth green tea ice cream.'),
('Ectoplasm Scoop', 'Lemon Lime', '/slime.png', 3.90, 'Citrus blend with a glowing slime look.'),
('Alien Brain', 'Melon', '/slime.png', 4.60, 'Sweet honeydew melon slime.'),
('Zombie Bite', 'Watermelon', '/slime.png', 4.10, 'Green shell with pink watermelon center.'),
('Slime Shake', 'Avocado', '/slime.png', 5.80, 'Creamy avocado slime shake.'),
('Bog Berry', 'Blueberry Lime', '/slime.png', 4.70, 'Tangy blueberry and lime slime.'),
('Creepy Crawler', 'Gummy Bear', '/slime.png', 5.00, 'Vanilla slime filled with gummy worms.'),
('Slime Float', 'Root Beer', '/slime.png', 4.90, 'Root beer with a scoop of slime ice cream.'),
('Grimer Delight', 'Grape', '/slime.png', 3.80, 'Purple grape with a hint of green slime.'),
('Sludgy Dough', 'Cookie Dough', '/slime.png', 5.30, 'Classic cookie dough dyed slime green.'),
('Ooze Bar', 'Coconut', '/slime.png', 3.50, 'Tropical coconut covered in slime glaze.'),
('Mossy Rock', 'Cookies & Cream', '/slime.png', 4.50, 'Oreo bits mixed in green slime ice cream.'),
('Slime Sandwich', 'Strawberry', '/slime.png', 4.20, 'Strawberry slime pressed between two cookies.'),
('Venom Scoop', 'Blackberry', '/slime.png', 4.60, 'Dark blackberry slime.'),
('Monster Mash', 'Bubblegum', '/slime.png', 3.90, 'Bright green bubblegum flavor.'),
('Slime Sorbet', 'Mango', '/slime.png', 4.40, 'Dairy-free mango slime sorbet.'),
('Goo Drop', 'Pineapple', '/slime.png', 3.60, 'Sweet pineapple slime drop.'),
('Slime Cake', 'Cheesecake', '/slime.png', 5.90, 'Rich cheesecake with slime topping.'),
('Swamp Parfait', 'Caramel', '/slime.png', 5.40, 'Layers of caramel and green slime.'),
('Ooze Truffle', 'Dark Chocolate', '/slime.png', 6.00, 'Decadent chocolate with a slime center.'),
('Slime Split', 'Banana', '/slime.png', 6.50, 'Classic banana split with slime sauce.'),
('Mega Slime', 'Cotton Candy', '/slime.png', 7.00, 'Giant scoop of cotton candy flavored slime.');
